name: Split Fonts

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag, e.g. normal is v1.330, patach version v1.330.1'
        required: false

jobs:
  build:
    name: get the fonts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: '20'

      - name: Download LxgwWenKai
        id: down1
        uses: robinraju/release-downloader@v1.10
        with:
          repository: lxgw/LxgwWenKai
          latest: true
          out-file-path: "tmp"
          fileName: '*.ttf'
      
      - name: Download LxgwWenKai-Screen
        id: down2
        uses: robinraju/release-downloader@v1.10
        with:
          repository: lxgw/LxgwWenKai-Screen
          latest: true
          out-file-path: "tmp"
          fileName: '*.ttf'

      - name: Download LxgwWenkai-TC
        id: down3
        uses: robinraju/release-downloader@v1.10
        with:
          repository: lxgw/LxgwWenkaiTC
          latest: true
          out-file-path: "tmp"
          fileName: '*.ttf'

      - name: Download LxgwWenkai-GB
        id: down4
        uses: robinraju/release-downloader@v1.10
        with:
          repository: lxgw/LxgwWenkaiGB
          latest: true
          out-file-path: "tmp"
          fileName: '*.ttf'

      - name: Check inputs Tag
        run: |
          if [ "${{ github.event.inputs.tag }}" != "null" ]; then
            echo "tag_name=${{ github.event.inputs.tag }}" >> "$GITHUB_ENV"
          else
            echo "tag_name=${{ steps.down1.outputs.tag_name }}" >> "$GITHUB_ENV"
          fi

          echo "tag_name is $tag_name"
          
      - name: Show files
        run: |
          ls -a
          ls tmp

      - name: Split fonts
        run: |
          npm install @konghayao/cn-font-split -g
          
          for i in $(echo "$(ls ./tmp)" | grep -i '\.ttf$')
          do
            font_name=$(echo "$i" | sed -E 's/(.+)\.ttf$/\1/i' | tr '[:upper:]' '[:lower:]')
            cn-font-split -i=./tmp/$i -o=./fonts/$font_name --renameOutputFont='[index][ext]'
            echo "@import url('./$font_name/result.css');" >> ./$font_name-style.css
            mv $font_name-style.css fonts/$font_name-style.css
          done

          echo "$tag_name" >> VERSION

          mv VERSION fonts/VERSION
          rm -rf ./tmp/
          ls -a

      - name: Auto Minify
        uses: nizarmah/auto-minify@v3

      - name: Commit files
        run: |
          mv index.html fonts/index.html
          cd fonts || exit 1
          git init
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]
          git checkout -b latest
          git status
          git add .
          git commit -m "update $tag_name" -a
          git tag $tag_name

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          tags: true
          directory: fonts
          branch: latest
